# Generated by Django 5.2.6 on 2025-10-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('system', 'Системи автоматичного поливу'), ('sprinkles', 'Розбризкувачі'), ('pumps', 'Насоси'), ('hoses', 'Шланги'), ('valves', 'Клапани'), ('sensors', 'Датчики вологості'), ('controllers', 'Контролери'), ('filters', 'Фільтри')], max_length=50, null=True),
        ),
    ]
