# Generated by Django 5.2.6 on 2025-10-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0003_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kititem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='kit',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
