# Generated by Django 5.2.6 on 2025-10-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0004_remove_kititem_quantity_kit_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='price',
        ),
    ]
