# Generated by Django 5.2.6 on 2025-10-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0005_remove_kit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='price_manual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Якщо заповнено, ця ціна буде використовуватись замість автоматичної', max_digits=10, null=True, verbose_name='Ціна вручну'),
        ),
    ]
