# Generated by Django 5.2.6 on 2025-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0006_kit_price_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='price_manual',
        ),
        migrations.AddField(
            model_name='kit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
