# Generated by Django 5.2.6 on 2025-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0007_remove_kit_price_manual_kit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
