# Generated by Django 5.2.6 on 2025-11-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0010_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sender',
            new_name='user',
        ),
    ]
