# Generated by Django 5.2.6 on 2025-11-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0011_rename_sender_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
