# Generated by Django 5.2.6 on 2025-11-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0013_serviceorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/', verbose_name='Зображення'),
        ),
    ]
