# Generated by Django 5.2.6 on 2025-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0015_promocode_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
