# Generated by Django 5.2.6 on 2025-11-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0016_promocode_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='used',
        ),
    ]
