# Generated by Django 5.2.6 on 2025-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0019_user_is_verified_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
