# Generated by Django 5.2.6 on 2025-11-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Watering', '0020_serviceorder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kititem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість в наборі'),
        ),
    ]
